apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-cicd
  template:
    metadata:
      labels:
        app: hello-cicd
    spec:
      containers:
        - name: hello-cicd
          image: rafkaihza78/hello-cicd:latest
          imagePullPolicy: Always     # 🔥 WAJIB SUPAYA WEB NYA SELALU UPDATE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-cicd-service
spec:
  type: LoadBalancer
  selector:
    app: hello-cicd
  ports:
    - port: 3000
      targetPort: 3000
